// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/content-page/faqs": {
            "get": {
                "description": "Retrieve list information of Faqs",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "2. Content Page"
                ],
                "summary": "Get Faqs",
                "parameters": [
                    {
                        "type": "integer",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "page",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/content-page/pages/{slug}": {
            "get": {
                "description": "Retrieve detailed information of a content page using its slug",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "2. Content Page"
                ],
                "summary": "Get Content Page by Slug",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Content Page Slug",
                        "name": "slug",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "{\"data\": content_page.DetailResponse, \"message\": \"\"}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "400": {
                        "description": "{\"data\": null, \"message\": \"Bad Request\"}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "{\"data\": null, \"message\": \"Internal Server Error\"}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Check application health status",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "1. Health Check"
                ],
                "summary": "Health Check",
                "responses": {
                    "200": {
                        "description": "{\"data\": null, \"message\": \"successfully checked\"}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    },
                    "500": {
                        "description": "{\"data\": null, \"message\": \"internal server error\"}",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/master/cities": {
            "get": {
                "description": "Mengambil master list cities",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "3. Master"
                ],
                "summary": "Get List Cities",
                "parameters": [
                    {
                        "type": "integer",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "province_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "search",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Berhasil mengambil data city",
                        "schema": {
                            "$ref": "#/definitions/master.SwaggerCityPagination"
                        }
                    }
                }
            }
        },
        "/master/district": {
            "get": {
                "description": "Mengambil master list district",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "3. Master"
                ],
                "summary": "Get List District",
                "parameters": [
                    {
                        "type": "string",
                        "name": "city_id",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "search",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Berhasil mengambil data district",
                        "schema": {
                            "$ref": "#/definitions/master.SwaggerDistrictPagination"
                        }
                    }
                }
            }
        },
        "/master/provincies": {
            "get": {
                "description": "Mengambil master list province",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "3. Master"
                ],
                "summary": "Get List Province",
                "parameters": [
                    {
                        "type": "integer",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "name": "search",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Berhasil mengambil data provinsi",
                        "schema": {
                            "$ref": "#/definitions/master.SwaggerProvincePagination"
                        }
                    }
                }
            }
        },
        "/order": {
            "post": {
                "description": "Membuat order baru dan menginisiasi pembayaran via Midtrans Snap",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "4. Order"
                ],
                "summary": "Checkout",
                "parameters": [
                    {
                        "description": "Checkout Request",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/order.CheckoutRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Order berhasil dibuat",
                        "schema": {
                            "$ref": "#/definitions/order.CheckoutResponse"
                        }
                    }
                }
            }
        },
        "/order/notification": {
            "post": {
                "description": "Merespons notifikasi webhook dari Midtrans (public endpoint, tanpa auth)",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "4. Order"
                ],
                "summary": "Handle Payment Notification",
                "parameters": [
                    {
                        "description": "Midtrans Notification Payload",
                        "name": "req",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/midtrans.NotificationPayload"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Notifikasi diproses",
                        "schema": {
                            "$ref": "#/definitions/order.NotificationResponse"
                        }
                    }
                }
            }
        },
        "/order/{id}/payment-link": {
            "post": {
                "description": "Membuat payment link Midtrans untuk order yang masih PENDING sehingga bisa dibagikan",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "4. Order"
                ],
                "summary": "Create Payment Link",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Order ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Payment link berhasil dibuat",
                        "schema": {
                            "$ref": "#/definitions/order.PaymentLinkResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "master.ListCityResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "province_id": {
                    "type": "string"
                }
            }
        },
        "master.ListDistrictResponse": {
            "type": "object",
            "properties": {
                "city_id": {
                    "type": "string"
                },
                "code": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "master.ListProvinceResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "master.SwaggerCityPagination": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/master.ListCityResponse"
                    }
                },
                "message": {
                    "type": "string",
                    "example": "OK"
                },
                "page": {
                    "type": "object",
                    "properties": {
                        "current": {
                            "type": "integer",
                            "example": 1
                        },
                        "size": {
                            "type": "integer",
                            "example": 10
                        },
                        "total": {
                            "type": "integer",
                            "example": 37
                        }
                    }
                }
            }
        },
        "master.SwaggerDistrictPagination": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/master.ListDistrictResponse"
                    }
                },
                "message": {
                    "type": "string",
                    "example": "OK"
                },
                "page": {
                    "type": "object",
                    "properties": {
                        "current": {
                            "type": "integer",
                            "example": 1
                        },
                        "size": {
                            "type": "integer",
                            "example": 10
                        },
                        "total": {
                            "type": "integer",
                            "example": 37
                        }
                    }
                }
            }
        },
        "master.SwaggerProvincePagination": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/master.ListProvinceResponse"
                    }
                },
                "message": {
                    "type": "string",
                    "example": "OK"
                },
                "page": {
                    "type": "object",
                    "properties": {
                        "current": {
                            "type": "integer",
                            "example": 1
                        },
                        "size": {
                            "type": "integer",
                            "example": 10
                        },
                        "total": {
                            "type": "integer",
                            "example": 37
                        }
                    }
                }
            }
        },
        "midtrans.NotificationPayload": {
            "type": "object",
            "properties": {
                "currency": {
                    "type": "string"
                },
                "expiry_time": {
                    "type": "string"
                },
                "fraud_status": {
                    "type": "string"
                },
                "gross_amount": {
                    "type": "string"
                },
                "merchant_id": {
                    "type": "string"
                },
                "order_id": {
                    "type": "string"
                },
                "payment_code": {
                    "type": "string"
                },
                "payment_type": {
                    "type": "string"
                },
                "settlement_time": {
                    "type": "string"
                },
                "signature_key": {
                    "type": "string"
                },
                "status_code": {
                    "type": "string"
                },
                "status_message": {
                    "type": "string"
                },
                "store": {
                    "type": "string"
                },
                "transaction_id": {
                    "type": "string"
                },
                "transaction_status": {
                    "type": "string"
                },
                "transaction_time": {
                    "type": "string"
                },
                "va_numbers": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/midtrans.VaNumber"
                    }
                }
            }
        },
        "midtrans.VaNumber": {
            "type": "object",
            "properties": {
                "bank": {
                    "type": "string"
                },
                "va_number": {
                    "type": "string"
                }
            }
        },
        "order.CheckoutItem": {
            "type": "object",
            "properties": {
                "qty": {
                    "type": "integer"
                },
                "variant_id": {
                    "type": "string"
                }
            }
        },
        "order.CheckoutRequest": {
            "type": "object",
            "required": [
                "address_id",
                "payment_method",
                "shipping_fee"
            ],
            "properties": {
                "address_id": {
                    "type": "string"
                },
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/order.CheckoutItem"
                    }
                },
                "payment_method": {
                    "type": "string"
                },
                "shipping_fee": {
                    "type": "number"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "order.CheckoutResponse": {
            "type": "object",
            "properties": {
                "expires_at": {
                    "type": "string"
                },
                "order_id": {
                    "type": "string"
                },
                "payment_token": {
                    "type": "string"
                },
                "payment_url": {
                    "type": "string"
                }
            }
        },
        "order.NotificationResponse": {
            "type": "object",
            "properties": {
                "order_id": {
                    "type": "string"
                },
                "processed": {
                    "type": "boolean"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "order.PaymentLinkResponse": {
            "type": "object",
            "properties": {
                "order_id": {
                    "type": "string"
                },
                "url": {
                    "type": "string"
                }
            }
        }
    },
    "tags": [
        {
            "name": "1. Health Check"
        },
        {
            "name": "2. Content Page"
        },
        {
            "name": "3. Master"
        }
    ]
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8085",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Website Api",
	Description:      "Api Documentation for Website",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
